[project]
name = "musicassistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "musicbrainzngs>=0.7.1",
    "pydantic-ai>=0.2.9",
    "python-dotenv>=1.1.0",
]
