"""Consolidate schema to current models

Revision ID: 38559f1f49c0
Revises: 003
Create Date: 2025-04-10 16:03:03.073769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38559f1f49c0'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_interactions_content_id', table_name='interactions')
    op.drop_index('ix_interactions_created_at', table_name='interactions')
    op.drop_index('ix_interactions_external_id', table_name='interactions')
    op.drop_index('ix_interactions_external_user_id', table_name='interactions')
    op.drop_index('ix_interactions_external_username', table_name='interactions')
    op.drop_index('ix_interactions_id', table_name='interactions')
    op.drop_index('ix_interactions_interaction_type', table_name='interactions')
    op.drop_index('ix_interactions_is_processed', table_name='interactions')
    op.drop_index('ix_interactions_persona_id', table_name='interactions')
    op.drop_index('ix_interactions_platform', table_name='interactions')
    op.drop_index('ix_interactions_response_id', table_name='interactions')
    op.drop_index('ix_interactions_sentiment', table_name='interactions')
    op.drop_index('ix_interactions_status', table_name='interactions')
    op.drop_index('ix_interactions_type', table_name='interactions')
    op.drop_table('interactions')
    op.drop_index('ix_platform_connections_id', table_name='platform_connections')
    op.drop_index('ix_platform_connections_is_active', table_name='platform_connections')
    op.drop_index('ix_platform_connections_persona_id', table_name='platform_connections')
    op.drop_index('ix_platform_connections_platform', table_name='platform_connections')
    op.drop_index('ix_platform_connections_platform_name', table_name='platform_connections')
    op.drop_index('ix_platform_connections_platform_user_id', table_name='platform_connections')
    op.drop_index('ix_platform_connections_username', table_name='platform_connections')
    op.drop_table('platform_connections')
    op.drop_index('ix_content_content_type', table_name='content')
    op.drop_index('ix_content_external_id', table_name='content')
    op.drop_index('ix_content_id', table_name='content')
    op.drop_index('ix_content_persona_id', table_name='content')
    op.drop_index('ix_content_platform', table_name='content')
    op.drop_index('ix_content_scheduled_time', table_name='content')
    op.drop_index('ix_content_status', table_name='content')
    op.drop_table('content')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_full_name', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_personas_id', table_name='personas')
    op.drop_index('ix_personas_name', table_name='personas')
    op.drop_table('personas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('personas_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('background', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('interests', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expertise', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('purpose', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='personas_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='personas_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_personas_name', 'personas', ['name'], unique=False)
    op.create_index('ix_personas_id', 'personas', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_full_name', 'users', ['full_name'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('content',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('content_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scheduled_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('published_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('media_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('content_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name='content_persona_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='content_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_content_status', 'content', ['status'], unique=False)
    op.create_index('ix_content_scheduled_time', 'content', ['scheduled_time'], unique=False)
    op.create_index('ix_content_platform', 'content', ['platform'], unique=False)
    op.create_index('ix_content_persona_id', 'content', ['persona_id'], unique=False)
    op.create_index('ix_content_id', 'content', ['id'], unique=False)
    op.create_index('ix_content_external_id', 'content', ['external_id'], unique=False)
    op.create_index('ix_content_content_type', 'content', ['content_type'], unique=False)
    op.create_table('platform_connections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('auth_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('platform_user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('profile_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_used', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('platform_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name='platform_connections_persona_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='platform_connections_pkey')
    )
    op.create_index('ix_platform_connections_username', 'platform_connections', ['username'], unique=False)
    op.create_index('ix_platform_connections_platform_user_id', 'platform_connections', ['platform_user_id'], unique=False)
    op.create_index('ix_platform_connections_platform_name', 'platform_connections', ['platform_name'], unique=False)
    op.create_index('ix_platform_connections_platform', 'platform_connections', ['platform'], unique=False)
    op.create_index('ix_platform_connections_persona_id', 'platform_connections', ['persona_id'], unique=False)
    op.create_index('ix_platform_connections_is_active', 'platform_connections', ['is_active'], unique=False)
    op.create_index('ix_platform_connections_id', 'platform_connections', ['id'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('interaction_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('external_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('external_username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sentiment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_processed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('response_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('content_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('platform_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('responded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name='interactions_content_id_fkey'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name='interactions_persona_id_fkey'),
    sa.ForeignKeyConstraint(['response_id'], ['content.id'], name='interactions_response_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='interactions_pkey')
    )
    op.create_index('ix_interactions_type', 'interactions', ['type'], unique=False)
    op.create_index('ix_interactions_status', 'interactions', ['status'], unique=False)
    op.create_index('ix_interactions_sentiment', 'interactions', ['sentiment'], unique=False)
    op.create_index('ix_interactions_response_id', 'interactions', ['response_id'], unique=False)
    op.create_index('ix_interactions_platform', 'interactions', ['platform'], unique=False)
    op.create_index('ix_interactions_persona_id', 'interactions', ['persona_id'], unique=False)
    op.create_index('ix_interactions_is_processed', 'interactions', ['is_processed'], unique=False)
    op.create_index('ix_interactions_interaction_type', 'interactions', ['interaction_type'], unique=False)
    op.create_index('ix_interactions_id', 'interactions', ['id'], unique=False)
    op.create_index('ix_interactions_external_username', 'interactions', ['external_username'], unique=False)
    op.create_index('ix_interactions_external_user_id', 'interactions', ['external_user_id'], unique=False)
    op.create_index('ix_interactions_external_id', 'interactions', ['external_id'], unique=False)
    op.create_index('ix_interactions_created_at', 'interactions', ['created_at'], unique=False)
    op.create_index('ix_interactions_content_id', 'interactions', ['content_id'], unique=False)
    # ### end Alembic commands ###
